use environment variables for interval_service_uuid

diff --git a/env b/env
--- a/env
+++ b/env
@@ -22,6 +22,19 @@ function trap_interrupt {
   trap "echo $@; exit;" INT
 }
 
+function test_command {
+  echo "$(pwd) : $@"
+  "$@"
+  local status=$?
+  if [ ${status} -ne 0 ]; then
+    echo
+    echo "--- error with $1" >&2
+    exit ${status}
+  fi
+  return ${status}
+}
+
+
 trap_interrupt " ! Caught User Interrupt, Exiting... ! "
 
 function run_sub_command {
